services:
  - name: docker
    image: docker:stable-dind
    capabilities:
     - all
    net: host
    binds:
     - /run/docker/cgroup:/sys/fs/cgroup
     - /etc/resolv.conf:/etc/resolv.conf
     - /var/lib/docker:/var/lib/docker
     - /lib/modules:/lib/modules
     - /etc/docker/daemon.json:/etc/docker/daemon.json
    command: ["/usr/local/bin/docker-init", "/usr/local/bin/dockerd"]
